# Generated by Django 4.0.6 on 2022-09-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='Uploaded Files/'),
        ),
    ]
