# Generated by Django 4.0.6 on 2022-09-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0008_alter_noticia_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='Uploaded Files/'),
        ),
    ]
